[tool.isort]
profile = "black"
py_version = 310
line_length = 120

[tool.black]
line-length = 120
target-version = 'py310'

[tool.flake8]
ignore = "E203"
max-line-length = 120

#[tool.mypy]
